# fly.toml app configuration file generated for lezack on 2023-09-17T21:21:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lezack"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
